### ISSUE TITLE
Background thread refuses to communicate past first cycle

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#10]
I'm not sure if this is a bug or more of a feature request.

```
 Turntabler.run do
   client = Turntabler::Client.new(EMAIL, PASSWORD, :room => ROOM, :user_id => USER_ID, :auth => AUTH)

 Thread.new {
    while 1 do
            sleep(5);
            client.room.say("Blah");                
            puts "Background process reporting"
            end
 }
```

When I try to run this I see Blah once, and never again.  I don't see background process reporting in the debug log either past the first one.  When I run the piece of demo code below I get the results I would expect.  Is there anything that can be done to make what I want to do possible? 

```
 #!/usr/bin/ruby

 Thread.new { 
while 1 do
    sleep 1 
    puts "Spam\n"
    end
}
 while 1 do 
sleep 1
end
```

**Comment by obrie** [comment]
Hey @FuzzySunshine -

When you're inside of a thread like that, you end up in the root fiber and can no longer call the Turntabler APIs.  If you throw a `begin`-`rescue` around your `while` loop, you'll see the exception that gets raised:

```
Turntabler APIs cannot be called from root fiber; use Turntabler.run { ... } instead
lib/turntabler/client.rb:512:in `rescue in wait'
lib/turntabler/client.rb:508:in `wait'
lib/turntabler/client.rb:154:in `api'
lib/turntabler/resource.rb:183:in `api'
lib/turntabler/room.rb:380:in `api'
lib/turntabler/room.rb:360:in `say'
```

To fix this, just change your call to the following:

``` ruby
TT.run { client.room.say("Blah") }
```

**Comment by StephanieSunshine** [comment]
Thank you that worked perfectly as well. :)

**Comment by StephanieSunshine** [comment]
Hi so using what you advised it seems that sleep still blocks the main loop from executing anything.  Is there anything that can be done to make that little piece of code sleep while the main loop continues to run?

**Comment by obrie** [comment]
That main loop stops because you're inside of an eventmachine. One easy way to avoid this is by using the `Turntabler.interactive` feature. That will cause the eventmachine to run in a separate thread instead of the main one.
