### ISSUE TITLE
client.room.current_song.enqueue queues song at the top of the queue

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#13]
It seems every time this is called that the song ends up at the top of the queue and not at the bottom.  Every time we snag a song with a command trigger we are also having to force the bot to skip it's turn because the song that was just snagged plays.

**Comment by obrie** [comment]
See the docs for `enqueue` -- http://rdoc.info/github/obrie/turntabler/master/Turntabler/Song:enqueue.  It takes a `:index` option for controlling where in the list to add it.
