### ISSUE TITLE
Multiple bots

### ISSUE THREAD

**Issue by solap** [obrie/turntabler#15]
Should the library support multiple bots? 
Has anyone tried it?
I've tried running two scripts at the same time and it fails.
I'm going to try running two bots within the same program, but wanted to see if anyone else has done it successfully.

**Comment by obrie** [comment]
You can run two bots like so:

``` ruby
require 'turntabler'

Thread.new do
  Turntabler.run do
    client = Turntabler::Client.new(EMAIL, PASSWORD, :room => ROOM)
    # ...
  end
end

Thread.new do
  Turntabler.run do
    client = Turntabler::Client.new(EMAIL2, PASSWORD2, :room => ROOM)
    # ...
  end
end
```

_However_, you must have a separate account for each bot.  You cannot have a single account be entered in multiple rooms.
