### ISSUE TITLE
Playlist reordering failing

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#16]
E, [2013-02-19T08:59:10.691789 #15570] ERROR -- : Command "playlist.reorder" failed with message: "api error (1)"...

```
 when "*skip"
   if client.room.current_dj == client.user
     client.room.current_song.skip
   else
     ((client.user.playlist.songs)[0]).move(:to_index => (client.user.playlist.songs).count+1)
   end  
```

I'm trying to move the song at the top of the playlist to the bottom of the playlist if the bot isn't djing.  Any suggestions?

**Comment by obrie** [comment]
`(client.user.playlist.songs).count+1` would be out of bounds since the index is zero-based.. what if you tried `client.user.playlist.songs.count` instead?

**Comment by StephanieSunshine** [comment]
I actually tried that first, I will try it again and reply back.  Also your room page from the API is missing :)

**Comment by StephanieSunshine** [comment]
Yea I just removed the +1 and same error as before.

**Comment by StephanieSunshine** [comment]
I just tried -1 as well thinking that maybe it's shifting it off the front and making the array actually smaller and i got the same error. :(

**Comment by StephanieSunshine** [comment]
Ok so i figured it out, i had to remove the :to_index => and it worked! :)

**Comment by obrie** [comment]
Good catch!  Also weird about the Room page... I'll have to look into that.  Thanks!

**Comment by obrie** [comment]
Looks like it was just a problem with rdoc.info -- that page should be fixed now.

**Comment by obrie** [comment]
Looks like it was just a problem with rdoc.info -- that page should be fixed now.
