### ISSUE TITLE
Playlist advancing incorrectly after a skip

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#17]
I've been working on a piece of code to advance the playlist when the dj isn't playing and that works correctly.  However when I try to skip while the bot is djing, the bot skips, but the playlist doesn't update correctly.  If the bot plays again, it will play the right song, but the top of the playlist array isn't forwarded.

```
 when "*skip"
 if client.room.current_dj == client.user
 #       ((client.user.playlist.songs)[0]).move((client.user.playlist.songs).count)
 client.room.current_song.skip
 else
 ((client.user.playlist.songs)[0]).move((client.user.playlist.songs).count)
 #((client.user.playlist.songs)[0]).skip
 end
 client.user.playlist.update
 client.room.say(trigger['response'])
```

I'm really confused as to why this is happening.  If you'd like to see this in action were in http://turntable.fm/express_yourself9 and openBot is the bot in question.  Ponyo is me.

**Comment by StephanieSunshine** [comment]
"Timeline"
startbot
ask bot what is the next song.  Response "Eyes Wide Open by Gotye"
ask bot to skip
ask bot what is the next song.  Response "What's It All About (Digitally Remastered) by Al Green"
ask bot to dj
bot plays "What's It All About (Digitally Remastered) by Al Green"
ask bot to skip while playing
ask bot what is the next song.  Response "What's It All About (Digitally Remastered) by Al Green"
bot plays "Tired Of Being Alone by Al Green"
ask bot what is the next song.  Response "What's It All About (Digitally Remastered) by Al Green"
ask bot to step down
ask bot what is the next song.  Response "What's It All About (Digitally Remastered) by Al Green"
ask bot to skip
ask bot what is the next song. Response "Tired Of Being Alone by Al Green"
ask bot to dj
bot plays "How Can You Mend A Broken Heart by Al Green"
ask bot what is the next song.  Response "Tired Of Being Alone by Al Green"
......

As you can gets out of sync as soon as i try to skip the song while playing but if I skip it on the ground it can catch up.  I tried to advance the playlist forward by hand and i'm pretty sure it advanced by two ( that's why that line is commented out, i borrowed it from the successful off stage skip )

**Comment by StephanieSunshine** [comment]
I think skip is actually moving it two places on it's own instead of one.  I moved the nextup list to the next three and it seems that skip by itself is moving the playlist forward by two instead of one.  Maybe I can correct this with move to prove this.

**Comment by StephanieSunshine** [comment]
It's not, what is happening is skip is not advancing the internal playlist but the one on turntables side is, and move is advancing both of them.  Skip needs a playlist forward built into it. :)

**Comment by obrie** [comment]
You're right -- the playlist doesn't get updated as changes are made in the room.  Let me think a little bit on how this should get handled.

**Comment by StephanieSunshine** [comment]
Thank you :)

**Comment by obrie** [comment]
This should be better now.  I'll tag a release so that you can pull it down -- lemme know if you run into anymore issues!

**Comment by StephanieSunshine** [comment]
Will do, I think i found another queue problem, but I was going to wait until this was fixed to debug.  I'll pull it right now and see what I can do.

Thanks for everything!
