### ISSUE TITLE
Detecting if someone fanned you & someone been removed from djing ( forcefully )

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#18]
Looking in client.on I don't see anything to detect if someone has fanned you ( like an :on_fanned ) and I don't see anything to tell if a dj has been removed by force ( :dj_force_removed maybe? ).

Any suggestions?

**Comment by obrie** [comment]
Good catch -- both are issues.. I'll have to look into that!

**Comment by obrie** [comment]
All set!  Lots of new events added :)

**Comment by StephanieSunshine** [comment]
You're awesome, thank you so much for creating such a wonderful library!
