### ISSUE TITLE
client.on :song_snagged broken in newest release

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#19]
This was working with my old bot, but since I updated to the newest version of the module, it broke in my old bot and my new bot doesn't want to act on it either.

```
 client.on :song_snagged do |snag|
   client.room.say('Someone thought highly of this song')
 end
```

**Comment by obrie** [comment]
Hmm I'm not seeing any issues with the snagged event -- can you tell me exactly what error you're seeing?

**Comment by StephanieSunshine** [comment]
I'm sorry for some reason it started to work again and I didn't change a line of code.  Maybe there was some sort or glitch update with turntable......O well
