### ISSUE TITLE
room.say missing roomid

### ISSUE THREAD

**Issue by jasonhazel** [obrie/turntabler#2]
When trying to speak in the room, I get the following error.

`E, [2013-01-01T17:19:02.236054 #30318] ERROR -- : Command "room.speak" failed with message: "roomid and userid required"`

Here  is the bot code I am using

`on :user_spoke do |message|
    # Respond to "/hello" command
    if (message.content =~ /^hi$/i)
      room.say("Hey?")
    end
  end`

if I call the api method directly with `api('room.speak', :text => 'hey', :roomid => room.id)` it works as expected.

It seems like it would be as simple as adding `:roomid => id` in [room.rb](https://github.com/obrie/turntabler/blob/master/lib/turntabler/room.rb#L359), but being new to gem creation I think I am doing something wrong so I can't confirm.

**Comment by solap** [comment]
I applied this change myself.
I implement the following line:

```
room.say("Hey! How are you?")
```

And get the following error:

```
D, [2013-01-08T01:50:03.356602 #6191] DEBUG -- : Message received: {"msgid"=>6, "err"=>"roomid and userid required", "success"=>false, "command"=>"response_received"}
```

Here is the code I changed:

```
def say(content)
  enter
  api('room.speak', :text => content, :roomid => id) # changed according to pull request, joel.
  true
end
```

This line works:

```
api('room.speak', :text => 'hey', :roomid => room.id)
```

**Comment by solap** [comment]
Ouch. I think the problem was that the gem was installed and so it wasn't loading my change. I uninstalled the gem and get a completely different problem.

```
/Users/user.name/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- turntabler (LoadError)
from /Users/user.name/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
from examples/chat_bot.rb:3:in `<main>'
```

Looks like I'm figuring out how to test/build gems tonight. :)

**Comment by solap** [comment]
woo-hoo!!! got the gem building and figured out what was wrong. your fix works.
THANKS!!!
