### ISSUE TITLE
enqueue missing in the newest version

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#21]
E, [2013-02-24T11:14:29.193917 #3666] ERROR -- : undefined method `enqueue'

**Comment by obrie** [comment]
As noted in the changelog -- `Rename Song#enqueue to Song#add and Song#dequeue to Song#remove` .. see https://github.com/obrie/turntabler/commit/a01996e77964546cb32ea82d9fcce6d764337e7b

Just as a heads up, you'll want to look out for that when going from a 0.X.0 => 0.Y.0 release.

**Comment by StephanieSunshine** [comment]
Cool thank you. I'll update my code.  I'm still figuring out githubfu. :)
