### ISSUE TITLE
playlist.add failing

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#23]
D, [2013-02-24T11:35:41.243017 #2260] DEBUG -- : Message received: {"msgid"=>19, "err"=>"Playlist not found", "success"=>false, "command"=>"response_received"} E, [2013-02-24T11:35:41.243396 #2260] ERROR -- : Command "playlist.add" failed with message: "Playlist not found" /var/lib/openshift/

I apologize ahead of time if the docs have been updated and I just can't read them at the moment.

```
 client.room.current_song.add( :index => (client.user.playlist.songs).count )
```

**Comment by obrie** [comment]
Ah this is interesting -- I believe this can happen if you're adding a song from someone else's playlist whose name is different than yours.  I'll look into that.

**Comment by obrie** [comment]
Thanks for the heads up -- should be fixed now :)

**Comment by StephanieSunshine** [comment]
Cool thank you.  Does that mean that turntabler went to 0.3.1 or do i need to pull from the git repo?

**Comment by obrie** [comment]
It's actually bumped out to 0.3.2 now

**Comment by StephanieSunshine** [comment]
Sweet! thank you :) :+1:
