### ISSUE TITLE
playlist.forget problem(?)

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#24]
So far everything is working very well ( thank you so much! ), except forget.  If a bot is dj'ing and you want it to forget the current song that is playing it will not skip and forget, instead it forgets the next song in the queue and doesn't skip at all.  

When the bot is on the floor, forget seems to work just fine.

Any suggestions ? :)

**Comment by obrie** [comment]
It's a little unclear in the documentation (and I should make it clear), but when a song starts playing it immediately gets tacked onto the end of the playlist to reflect the state of the queue.  If you want to forget the song playing for the user, then I'd either do: `room.current_song.remove` or `user.playlist.songs.last.remove`

**Comment by StephanieSunshine** [comment]
Thank you :)

This worked for me:

```
 client.room.current_song.skip
 client.user.playlist.songs.last.remove
```
