### ISSUE TITLE
{:notify_dj=>false} is an invalid value

### ISSUE THREAD

**Issue by jasonhazel** [obrie/turntabler#25]
This code: `user.preferences.update(:notify_dj => false)`
Throws this error: `{:notify_dj=>false} is an invalid value; must be one of: notify_dj, notify_fan, notify_news, notify_random, facebook_awesome, facebook_join, facebook_dj`

I'm using the example found in the documentation: http://rdoc.info/github/obrie/turntabler/master/Turntabler/Preferences#update-instance_method

**Comment by obrie** [comment]
Thanks for the heads up!  -- this has been released in 0.3.3.
