### ISSUE TITLE
song.skip is causing a fatal error

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#26]
Hi, turntable has been having alot of issues with songs getting stuck lately, so I tried to add this piece of code:

```
    client.on :song_started do |song|
            EventMachine::Timer.new(song.length+5) do
                    song.skip
                    end
            end
```

And i'm noticing that this is throwing a fatal error and i'm not sure if thats correct.

My work around seems to be:

```
    client.on :song_started do |song|
            EventMachine::Timer.new(song.length+5) do
                    song.skip if (client.room.current_song == song) && (client.room.current_dj == client.user)
                    end
            end
```

Which seems to work, but i'm wondering, should this really be a fatal error?

**Comment by obrie** [comment]
Are you on the latest v0.3.3?  A recent change was made to the skip API that seems related to the error you're seeing.

**Comment by StephanieSunshine** [comment]
Probably not, I'll check it when I get back to the house :)

**Comment by StephanieSunshine** [comment]
I needed updates you are right, i haven't undid my code yet to see if it solved the problem, but i'll take your word for it :)
