### ISSUE TITLE
:song_voted question

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#29]
Hi, looking at your example i'm curious how does one determine who voted and which direction they voted?  Thank you :)

client.on :song_voted do |song| # Song
  puts song.up_votes_count
  puts song.down_votes_count
  puts song.votes
  # ...
end

**Comment by obrie** [comment]
`song.votes` should do the trick -- See http://rdoc.info/github/obrie/turntabler/master/Turntabler/Song:votes for details .. specifically the notes for that method and the return type.
