### ISSUE TITLE
Modifying the Profile

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#33]
Is there anyway to edit a bot's profile, specifically the about me section?  Many people have been asking me for something like this in our bots and looking in the API the only thing I could find was the client.about which claimed it was read-only.

Is there any easy way to do this?

**Comment by jasonhazel** [comment]
There is a very easy way to do this.  Here is an example of how I do it.

```
TT.run(EMAIL, PASSWORD, :room => ROOM, :reconnect_wait => 30) do  
    user.update {
        about: "Some stuff about me.",
        hangout: 'The room where I hangout.'
    }
end
```

**Comment by obrie** [comment]
@mrhazel's got it -- that should do the trick.
