### ISSUE TITLE
The API link is broke

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#35]
Please fix, i'm sure it's something really simple :)

http://rdoc.info/github/obrie/turntabler/master/frames

p.s. thanks for the new release :) 0.3.4 has been much stabler, and I just saw you released 0.3.5!

Congrats!

**Comment by jasonhazel** [comment]
I used the little form that is available on the error page, and the documentation has been re-generated.  You should be able to access it now.

**Comment by StephanieSunshine** [comment]
Thank you!  I tried poking at it and couldn't figure it out this morning.
