### ISSUE TITLE
client.user I think is broke

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#36]
This was tested against 0.3.4 so I apologise if this has been fixed in 0.3.5 and I just need to update.

The documentation is down right now, but looking into the code itself I found that client.user(id) should return a valid turntable user and itself when nil.  It seems when I call it no matter what I do I end up with self.  My userid is the 4ea8.....
## Code Example:

```
    if ( message.content.match(/^.bd_idle_lookup/))
    now = Time.new().to_i
            $antiIdle.each do |dj|
                    user = client.user(dj['user'])
                    client.room.say("#{dj['user']} = #{user.name} Idle: #{now - dj['timer'].to_i}")
            end
            client.room.say(client.user('4ea8d05fa3f751271d024366').name)
    end
```
## Output

4ea8d05fa3f751271d024366 = neuroBot Idle: 6
50030d32eb35c12c660001e4 = neuroBot Idle: 7
neuroBot

**Comment by jasonhazel** [comment]
I'm getting the same thing.  Regardless of what id is passed, it appears that the details are for the bot.

Question though, @FuzzySunshine.  What is contained in $antiIdle?  I assume it is just a list of id strings.  If so, have you thought about storing the actual user objects instead of just the id?  If you did it that way, then you wouldn't need a call to client.user, you could just do `dj.name`.

**Comment by StephanieSunshine** [comment]
```
            if newdj
                    a_newdj = {}
                    a_newdj['user'] = ndj.id
                    a_newdj['warned'] = false
                    a_newdj['booted'] = false
                    a_newdj['timer'] = now.to_i
                    mydjs.push(a_newdj)
                    end
```

$antiidle is a array of a_newdj hashes because marshal dump wouldn't let me serialize the users themselves, I had to resort to using the userid only.

Looking at the API http://rdoc.info/github/obrie/turntabler/master/Turntabler/Client:user

"Gets the current authorized user or builds a new user bound to the given user id."

Looking at his example in the API I thought this was the way we built user objects from userids.  I don't have a problem posting the whole anti-idle function, but it's basically just massaging the array and trying to copy the data from a local variable into the global variable.  I understand that globals are evil, but it was the simplest way to maintain consistent data against the function.  From what I understand about Ruby ( and mind you I'm no Ruby expert by any stretch of the imagination ), is that all complex data structures are copied by reference and not actually duplicating the structure in a new memory allocation and when trying to copy a complex structure ( say an array of hashes ) that the data needs to be serialized in and out of marshal to actually be copied.  From my understanding that is if you have a complex structure in a local variable ( say in a function ) and you try to copy that variable into another ( a global for this case ) that as soon as you lose scope ( leave the function ) that the reference will disappear because the code block is no longer in scope. 

So if you would like to see the whole thing, i'm happy to post it, but i'll refrain until you request it because i'd rather not spam the issue section over things that aren't api related.

**Comment by jasonhazel** [comment]
I'm far from a Ruby expert as well, so we're on the same page. :)

The API does state that the way you're trying to use it should work, I'm just thinking of maybe a way to work around this bug until we get some more clarification.  

You already have the user object (ndj), so why create another one?  Maybe trying something more along these lines would work (completely untested, but should work).

```
if newdj
    mydjs << {
        user:   ndj,
        warned: false,
        booted: false,
        timer:  now.to_i
    }
end
```

Then, the code from the original post would look something like this

```
if ( message.content.match(/^.bd_idle_lookup/))
  now = Time.new().to_i
  $antiIdle.each do |dj|
    client.room.say("#{dj[:user].id} = #{dj[:user].name} Idle: #{now - dj[:timer].to_i}")
  end
end
```

**Comment by StephanieSunshine** [comment]
Here, I pulled that code out of context, here is the whole anti idle function.  See if this helps shed some light on the subject

```
    def processAntiIdle(client, user, loc)
    #Validate list of dj's is current
    mydjs = []
    b_mydjs = []
    now = Time.new()
    pp "Anti-Idle Processing"
    #Add any new ones that did just join
    client.room.djs.each do |ndj|
            newdj = true
            $antiIdle.each do |odj|
                    newdj = false if odj['user'] == ndj.id
                    mydjs.push(odj) if odj['user'] == ndj.id
                    end
            if newdj
                    a_newdj = {}
                    a_newdj['user'] = ndj.id
                    a_newdj['warned'] = false
                    a_newdj['booted'] = false
                    a_newdj['timer'] = now.to_i
                    mydjs.push(a_newdj)
                    end
            end

    mydjs.each do |dj|
            dj['timer'] = now if user.id == dj['user']
            b_mydjs.push(dj) if client.room.djs.include?(client.user(dj['user']))
            end
    mydjs = []
    #Ok validate they haven't hit one of the clips
    b_mydjs.each do |dj|

            if ( now.to_i - dj['timer'].to_i ) > $botData['pkg_b_data']['ai_msg_t'].to_i
                    #boot
                    client.room.say($botData['pkg_b_data']['ai_msg'])
                    client.user(dj['user']).removedj
                    #dj['booted'] = true
            elsif (( now.to_i - dj['timer'].to_i ) > $botData['pkg_b_data']['ai_w_msg_t'].to_i) and (!dj['warned'])
                    #Warn
                    #Flag
                    client.room.say($botData['pkg_b_data']['ai_w_msg'])
                    dj['warned'] = true
            end
            mydjs.push(dj) if !dj['booted']
            end

    b_mydjs = Marshal.load(Marshal.dump(mydjs)) #overwrite the reference
    $antiIdle = Marshal.load(Marshal.dump(b_mydjs)) #overwrite the reference
    end
```

**Comment by StephanieSunshine** [comment]
for the record I am aware of the bug around removedj ( it should be remove_dj I believe )

**Comment by jasonhazel** [comment]
I have absolutely no experience with Marshal, so I don't know how much help I'll actually be.  I think that moving things into classes may help.  Instead of using Marshal, you could just set the value of an instance variable.

I'd like to continue helping you out, but we've drifted outside of the scope of this issue.  If you'd like, I can jump on TTFM when I get home from work and go over things with you.

Since you admitted to not being the best with Ruby, have you read over the style guide? It has helped me out a lot. https://github.com/bbatsov/ruby-style-guide

**Comment by StephanieSunshine** [comment]
I figured out a different way to do it and I also re-wrote the bot into a more oop style then a top down style.  I saw a place in the api manual that claimed to do the same thing but I forget what it's name is and my problem has been solved so I'm closing this.
