### ISSUE TITLE
Some examples not working

### ISSUE THREAD

**Issue by solap** [obrie/turntabler#6]
i'm using the code unmodified.

when i run chat_bot.rb, my bot logs into the room, but when i type /hello it gives me the following error:

```
E, [2013-01-06T02:15:49.389390 #35164] ERROR -- : undefined local variable or method `client' for #<Turntabler::Client:0x007fc768053318>
```

various errors when i run other examples. don't know where to start. i suspect it's setup or config so i don't want to start trying to fix code, but maybe others are seeing the same thing?

**Comment by jasonhazel** [comment]
Try taking client out.

```
TT.run(EMAIL, PASSWORD, :room => ROOM) do
  on :user_spoke do |message|
    # Respond to "/hello" command
    if (message.content =~ /^\/hello$/)
      user.say("Hey!")
    end
  end
end
```

**Comment by solap** [comment]
thanks for responding. same problem:

```
D, [2013-01-07T05:55:42.198489 #1460] DEBUG -- : Message received: {"command"=>"speak", "userid"=>"whatever", "name"=>"whatever", "roomid"=>"whatever", "text"=>"/hello"}
E, [2013-01-07T05:55:42.203919 #1460] ERROR -- : undefined local variable or method `client' for #<Turntabler::Client:whatever>
examples/chat_bot.rb:13:in `block (2 levels) in <main>'
```

i'm using the gem, btw. 
any ideas?

**Comment by jasonhazel** [comment]
Try replacing `user.say("Hey!")` with `puts message.inspect` and let's see what happens.

I'm currently running a locally patched version of the gem, but once we see the output of the inspect I should be running the same gem.

**Comment by solap** [comment]
it gets the message ok.
    <Turntabler::Message:0x007f82b1905e30 @content="/hello">

error is gone now that the "client" line is removed.

**Comment by jasonhazel** [comment]
Yeah, you don't want to use client in the examples.  instead of `client.user.say` you want `user.say`

**Comment by jasonhazel** [comment]
Also, are a couple bugs when it comes to chat messages.  room.say is missing the room id (i've put in a pull request for this) and chat messages are missing the user information. Everything else seems to be working pretty good though.

**Comment by solap** [comment]
I can use user.say, but I have to remove:

```
message.sender.name
```

from the line.

When I just use message.sender.name I get this:

```
E, [2013-01-07T06:23:04.606310 #1727] ERROR -- : undefined method `name' for nil:NilClass
examples/chat_bot.rb:17:in `block (2 levels) in <main>'
```

Do these examples work for some? I'm just wondering if my setup is whacked?

In part, I'm using this project to help me learn Ruby. So I'm trying to get to a working state before I really dig in.

**Comment by jasonhazel** [comment]
You're not the only one.  The message object does not contain the user information, so message.sender is nil. 

I was working on my own version of this project to learn Ruby until I found out about this one.

**Comment by solap** [comment]
Got it. Thanks!

**Comment by obrie** [comment]
Thanks for all the notes guys!  These examples should be working now :)
