### ISSUE TITLE
client.song.enqueue failing

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#8]
```
if level_1_acl.include?(message.sender.id) && message.content =~ /^\/snag$/
    client.song.enqueue
    client.song.snag
    client.room.say("Snagged. Thank you")
end
```

E, [2013-01-08T23:11:04.823980 #4140] ERROR -- : wrong number of arguments (0 for 1)
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:398:in `song'
./seriousBot.rb:64:in`block (2 levels) in <main>'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/handler.rb:51:in `call'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/handler.rb:51:in`block in run'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/handler.rb:49:in `each'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/handler.rb:49:in`run'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:453:in `block in on_message'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:452:in`each'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:452:in `on_message'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:102:in`block in connect'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/connection.rb:130:in `call'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/connection.rb:130:in`block in dispatch'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler.rb:89:in `call'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler.rb:89:in`block (2 levels) in run'
/var/lib/gems/1.9.1/gems/em-synchrony-1.0.2/lib/em-synchrony.rb:26:in `call'
/var/lib/gems/1.9.1/gems/em-synchrony-1.0.2/lib/em-synchrony.rb:26:in`block (2 levels) in synchrony'

Examples:

song.enqueue(:index => 1)   # => true  

(From http://rdoc.info/github/obrie/turntabler/master/frames/Turntabler/Room)

Using the example to the letter, I end up with the exact same error message.

**Comment by obrie** [comment]
You're attempting to call `Turntabler::Client#song` which is for song lookup (see http://rdoc.info/github/obrie/turntabler/master/Turntabler/Client:song)

If you want the current song being played, see `Turntabler::Room#current_song` (http://rdoc.info/github/obrie/turntabler/master/Turntabler/Room:current_song)

To then enqueue the current song, you would:

``` ruby
client.room.current_song.enqueue
```

**Comment by StephanieSunshine** [comment]
Thank you.  That worked perfectly
