### ISSUE TITLE
client.user.say is sending pms to the bot instead of the person triggering the event

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#9]
If you look at the debug the bot is trying to reply to itself rather then the person triggering it.

D, [2013-01-09T00:23:54.662153 #4565] DEBUG -- : Message received: {"command"=>"speak", "userid"=>"4ea8d05fa3f751271d024366", "name"=>"xxxxxxxxxxxx", "roomid"=>"50b9c49faaa5cd76060cdb84", "text"=>"/userids"}

D, [2013-01-09T00:23:54.663090 #4565] DEBUG -- : Message sent: {:clientid=>"1357719760-0.9903725504889215", :userid=>"5098bb36eb35c15965691ada", :userauth=>"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", :receiverid=>"5098bb36eb35c15965691ada", :text=>"Test", :api=>"pm.send", :msgid=>15}

Example from chat_bot.rb:
  on :user_spoke do |message|
    # Respond to "/hello" command
    if (message.content =~ /^\/hello$/)
      client.user.say("Hey! How are you @#{message.sender.name}?")
    end
  end

My code:

```
if level_1_acl.include?(message.sender.id) && message.content =~ /^\/userids$/
  client.user.say("Test")
end
```

**Comment by obrie** [comment]
That's expected -- `client.user` refers to the user the bot is logged in with.  The examples were incorrect -- they should have been using `message.sender` and were updated to do so.  Thanks for the note!

**Comment by StephanieSunshine** [comment]
Thank you that worked perfectly too! :)
